### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by giacomoscoccia** [TomByrne/s3-cli-windows#1]
Hi!

We are happily using your command and it worked flawless. 

Today we encounter an issue on a specific server. 
The server is a Windows Server 2008 R2 Standard Service Pack 1 64 bit
## Here it is what happened

s3.exe version 2.0 - check for updates at http://s3.codeplex.com

Using MIME type text/plain
prova/pippo/Nuovo documento di testo.txt
Exception has been thrown by the target of an invocation.
   in System.RuntimeMethodHandle._InvokeConstructor(Object[] args, SignatureStru
ct& signature, IntPtr declaringType)
   in System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, B
inder binder, Object[] parameters, CultureInfo culture)
   in System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Obje
ct[] args)
   in System.Security.Cryptography.MD5.Create()
   in com.amazon.s3.AWSAuthConnection.calculateMD5(Stream str, Int64 startByte,
Int64 bytes)
   in com.amazon.s3.AWSAuthConnection.put(String bucket, String key, Stream str,
 SortedList headers, Int64 startByte, Int64 bytes)
   in com.amazon.s3.AWSAuthConnection.put(String bucket, String key, Stream str,
 SortedList headers)
   in s3.Commands.Put.Execute()
##    in s3.Program.Main(String[] originalArgs)

We think that something related with .NET Framewwork 2.0 is missing or corrupted, but we can't realize what is problem.

It happen with s3.exe version 2.0 and also with version 1.7 with patch 5369 (delete key command)

Any suggestion?

Thanks in advance
Giacomo

**Comment by TomByrne** [comment]
Hey, I'm really only using the **get** operation, and don't really have time to provide support.
Happy to merge in pull requests, but otherwise I won't really be able to help on this, sorry.

**Comment by giacomoscoccia** [comment]
We found then cause.
It was a security settings on that server.

Here it is the link that helped us to solve issue
[link](http://www.asptricks.net/2015/10/fips-validated-cryptographic-algorithms.html)

Bye!
